name: Release Please

on:
  push:
    branches:
      - main
    
defaults:
  run:
    working-directory: Assets/Scripts

jobs:
  check_and_generate_files:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: com.obert.ui
          path: Assets/Scripts
          
